---
ops_vrfs:
  - name: vrf_default
    ports: [ eth1, eth2, eth3 ]
    bgp_routers:
      - as_number: 2002
        router_id: 2.2.2.2
        networks: [12.1.1.0/24, 12.2.1.0/24, 12.3.1.0/24]
        neighbors:
          - address: 12.1.1.2
            remote_as: 1001
          - address: 12.2.1.2
            remote_as: 1002
          - address: 12.3.1.2
            remote_as: 1003

ops_intf_admin_state: up

ops_interfaces:
  - name: eth1
  - name: eth2
  - name: eth3

ops_ports:
  - name: eth1
    ipv4_address: 12.1.1.1/24
  - name: eth2
    ipv4_address: 12.2.1.1/24
  - name: eth3
    ipv4_address: 12.3.1.1/24
